<?php

class FbFacepile extends CWidget
{
    public $url;
    public $action;
    public $numRows;
    public $size;
    public $showCount = true;
    public $width = 300;
    public $colorscheme;
    public $htmlOptions = array();

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}