<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'just now' => 'Juuri nyt',
  '{n} day ago|{n} days ago' => '{n} päivä sitten|{n} päivää sitten',
  '{n} hour ago|{n} hours ago' => '{n} tunti sitten|{n} tuntia sitten',
  '{n} minute ago|{n} minutes ago' => '{n} minuutti sitten|{n} minuuttia sitten',
  '{n} month ago|{n} months ago' => '{n} kuukausi sitten|{n} kuukausia sitten',
  '{n} year ago|{n} years ago' => '{n} vuosi sitten|{n} vuosia sitten',
);
